# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(161A1C)
$foreground = rgb(A7EFFF)
$color0 = rgb(3D4143)
$color1 = rgb(01161C)
$color2 = rgb(01161C)
$color3 = rgb(01161C)
$color4 = rgb(015467)
$color5 = rgb(015467)
$color6 = rgb(049EBF)
$color7 = rgb(79E0F6)
$color8 = rgb(559DAD)
$color9 = rgb(011D25)
$color10 = rgb(011D25)
$color11 = rgb(011D25)
$color12 = rgb(017089)
$color13 = rgb(017089)
$color14 = rgb(05D2FF)
$color15 = rgb(79E0F6)
