# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates

# OPACITY DISABLED
windowrule = match:tag browser, opacity 1.0 1.0
windowrule = match:tag projects, opacity 1.0 1.0
windowrule = match:tag im, opacity 1.0 1.0
windowrule = match:tag multimedia, opacity 1.0 1.0
windowrule = match:tag file-manager, opacity 1.0 1.0
windowrule = match:tag terminal, opacity 1.0 1.0
windowrule = match:tag settings, opacity 1.0 1.0
windowrule = match:tag viewer, opacity 1.0 1.0
windowrule = match:tag wallpaper, opacity 1.0 1.0
windowrule = match:class ^(gedit|org.gnome.TextEditor|mousepad)$, opacity 1.0 1.0
windowrule = match:class ^(deluge)$, opacity 1.0 1.0
windowrule = match:class ^(seahorse)$, opacity 1.0 1.0
windowrule = match:title ^(Picture-in-Picture)$, opacity 1.0 1.0


# terminal tags
windowrule = match:tag terminal, opacity 1.0 override 0.9 override
windowrule = match:class ^(kitty)$, opacity 1.0 override 1.0 override
windowrule = match:class ^(kitty-dropterm)$, opacity 0.9 0.8
windowrule = match:class ^([Tt]hunderbird|org.gnome.Evolution)$, tag +email
windowrule = match:class ^(eu.betterbird.Betterbird)$, tag +email