# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #A7EFFF
background         #161A1C
cursor             #548692

active_tab_foreground     #161A1C
active_tab_background     #A7EFFF
inactive_tab_foreground   #A7EFFF
inactive_tab_background   #161A1C

active_border_color   #A7EFFF
inactive_border_color #161A1C
bell_border_color     #01161C

color0      #3D4143
color1		#01161C
color2		#01161C
color3		#01161C
color4		#015467
color5		#015467
color6		#049EBF
color7		#79E0F6
color8		#559DAD
color9		#011D25
color10		#011D25
color11		#011D25
color12		#017089
color13		#017089
color14		#05D2FF
color15		#79E0F6
